# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Sat May  4 17:14:28 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName(_fromUtf8("main_window"))
        main_window.resize(1159, 461)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_window.sizePolicy().hasHeightForWidth())
        main_window.setSizePolicy(sizePolicy)
        main_window.setMinimumSize(QtCore.QSize(0, 0))
        main_window.setBaseSize(QtCore.QSize(0, 0))
        self.verticalLayoutWidget = QtGui.QWidget(main_window)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 431, 281))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.graph_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.graph_layout.setMargin(0)
        self.graph_layout.setObjectName(_fromUtf8("graph_layout"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(main_window)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(460, 20, 160, 281))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.method_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.method_layout.setMargin(0)
        self.method_layout.setObjectName(_fromUtf8("method_layout"))
        self.rb1 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.rb1.setChecked(True)
        self.rb1.setObjectName(_fromUtf8("rb1"))
        self.method_group = QtGui.QButtonGroup(main_window)
        self.method_group.setObjectName(_fromUtf8("method_group"))
        self.method_group.addButton(self.rb1)
        self.method_layout.addWidget(self.rb1)
        self.rb2 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.rb2.setObjectName(_fromUtf8("rb2"))
        self.method_group.addButton(self.rb2)
        self.method_layout.addWidget(self.rb2)
        self.rb3 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.rb3.setObjectName(_fromUtf8("rb3"))
        self.method_group.addButton(self.rb3)
        self.method_layout.addWidget(self.rb3)
        self.rb4 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.rb4.setObjectName(_fromUtf8("rb4"))
        self.method_group.addButton(self.rb4)
        self.method_layout.addWidget(self.rb4)
        self.rb5 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.rb5.setObjectName(_fromUtf8("rb5"))
        self.method_group.addButton(self.rb5)
        self.method_layout.addWidget(self.rb5)
        self.rb6 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.rb6.setObjectName(_fromUtf8("rb6"))
        self.method_group.addButton(self.rb6)
        self.method_layout.addWidget(self.rb6)
        self.rb7 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.rb7.setObjectName(_fromUtf8("rb7"))
        self.method_group.addButton(self.rb7)
        self.method_layout.addWidget(self.rb7)
        self.formLayoutWidget = QtGui.QWidget(main_window)
        self.formLayoutWidget.setGeometry(QtCore.QRect(460, 320, 160, 141))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.params_layout = QtGui.QFormLayout(self.formLayoutWidget)
        self.params_layout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.params_layout.setMargin(0)
        self.params_layout.setObjectName(_fromUtf8("params_layout"))
        self.x_Left_Label = QtGui.QLabel(self.formLayoutWidget)
        self.x_Left_Label.setObjectName(_fromUtf8("x_Left_Label"))
        self.params_layout.setWidget(0, QtGui.QFormLayout.LabelRole, self.x_Left_Label)
        self.x_Left_Line_Edit = QtGui.QLineEdit(self.formLayoutWidget)
        self.x_Left_Line_Edit.setObjectName(_fromUtf8("x_Left_Line_Edit"))
        self.params_layout.setWidget(0, QtGui.QFormLayout.FieldRole, self.x_Left_Line_Edit)
        self.x_Right_Label = QtGui.QLabel(self.formLayoutWidget)
        self.x_Right_Label.setObjectName(_fromUtf8("x_Right_Label"))
        self.params_layout.setWidget(1, QtGui.QFormLayout.LabelRole, self.x_Right_Label)
        self.x_Right_Line_Edit = QtGui.QLineEdit(self.formLayoutWidget)
        self.x_Right_Line_Edit.setObjectName(_fromUtf8("x_Right_Line_Edit"))
        self.params_layout.setWidget(1, QtGui.QFormLayout.FieldRole, self.x_Right_Line_Edit)
        self.update_button = QtGui.QPushButton(self.formLayoutWidget)
        self.update_button.setObjectName(_fromUtf8("update_button"))
        self.params_layout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.update_button)
        self.verticalLayoutWidget_3 = QtGui.QWidget(main_window)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 320, 431, 141))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.function_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.function_layout.setMargin(0)
        self.function_layout.setObjectName(_fromUtf8("function_layout"))
        self.function_horiz = QtGui.QHBoxLayout()
        self.function_horiz.setObjectName(_fromUtf8("function_horiz"))
        self.func_label = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.func_label.setMinimumSize(QtCore.QSize(30, 0))
        self.func_label.setObjectName(_fromUtf8("func_label"))
        self.function_horiz.addWidget(self.func_label)
        self.f_input = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.f_input.setObjectName(_fromUtf8("f_input"))
        self.function_horiz.addWidget(self.f_input)
        self.function_layout.addLayout(self.function_horiz)
        self.adiv_horiz = QtGui.QHBoxLayout()
        self.adiv_horiz.setObjectName(_fromUtf8("adiv_horiz"))
        self.adiv_label = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.adiv_label.setObjectName(_fromUtf8("adiv_label"))
        self.adiv_horiz.addWidget(self.adiv_label)
        self.F_input = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.F_input.setObjectName(_fromUtf8("F_input"))
        self.adiv_horiz.addWidget(self.F_input)
        self.function_layout.addLayout(self.adiv_horiz)
        self.results_horiz = QtGui.QHBoxLayout()
        self.results_horiz.setObjectName(_fromUtf8("results_horiz"))
        self.calculated_horiz = QtGui.QHBoxLayout()
        self.calculated_horiz.setObjectName(_fromUtf8("calculated_horiz"))
        self.calculated_label = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.calculated_label.setObjectName(_fromUtf8("calculated_label"))
        self.calculated_horiz.addWidget(self.calculated_label)
        self.calculated_result = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.calculated_result.setObjectName(_fromUtf8("calculated_result"))
        self.calculated_horiz.addWidget(self.calculated_result)
        self.results_horiz.addLayout(self.calculated_horiz)
        self.error_horiz = QtGui.QHBoxLayout()
        self.error_horiz.setObjectName(_fromUtf8("error_horiz"))
        self.error_label = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.error_label.setObjectName(_fromUtf8("error_label"))
        self.error_horiz.addWidget(self.error_label)
        self.error_calculated = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.error_calculated.setObjectName(_fromUtf8("error_calculated"))
        self.error_horiz.addWidget(self.error_calculated)
        self.results_horiz.addLayout(self.error_horiz)
        self.function_layout.addLayout(self.results_horiz)
        self.quad_method_table = QtGui.QTableWidget(main_window)
        self.quad_method_table.setGeometry(QtCore.QRect(630, 160, 501, 279))
        self.quad_method_table.setMinimumSize(QtCore.QSize(0, 0))
        self.quad_method_table.setSizeIncrement(QtCore.QSize(0, 0))
        self.quad_method_table.setAutoFillBackground(False)
        self.quad_method_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.quad_method_table.setAlternatingRowColors(True)
        self.quad_method_table.setGridStyle(QtCore.Qt.SolidLine)
        self.quad_method_table.setObjectName(_fromUtf8("quad_method_table"))
        self.quad_method_table.setColumnCount(3)
        self.quad_method_table.setRowCount(7)
        item = QtGui.QTableWidgetItem()
        self.quad_method_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.quad_method_table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.quad_method_table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.quad_method_table.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.quad_method_table.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.quad_method_table.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.quad_method_table.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.quad_method_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.quad_method_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.quad_method_table.setHorizontalHeaderItem(2, item)
        self.quad_method_table.horizontalHeader().setVisible(True)
        self.quad_method_table.horizontalHeader().setDefaultSectionSize(147)
        self.quad_method_table.horizontalHeader().setMinimumSectionSize(50)
        self.quad_method_table.horizontalHeader().setStretchLastSection(False)
        self.quad_method_table.verticalHeader().setDefaultSectionSize(36)
        self.quad_method_table.verticalHeader().setHighlightSections(True)
        self.quad_method_table.verticalHeader().setMinimumSectionSize(30)
        self.quad_method_table.verticalHeader().setStretchLastSection(False)
        self.verticalLayoutWidget_5 = QtGui.QWidget(main_window)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(630, 20, 501, 121))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.method_comparison_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.method_comparison_layout.setMargin(0)
        self.method_comparison_layout.setObjectName(_fromUtf8("method_comparison_layout"))
        self.rl_rr_horiz_layout = QtGui.QHBoxLayout()
        self.rl_rr_horiz_layout.setObjectName(_fromUtf8("rl_rr_horiz_layout"))
        self.rl_label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.rl_label.setMinimumSize(QtCore.QSize(111, 0))
        self.rl_label.setObjectName(_fromUtf8("rl_label"))
        self.rl_rr_horiz_layout.addWidget(self.rl_label)
        self.rl_check = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.rl_check.setText(_fromUtf8(""))
        self.rl_check.setObjectName(_fromUtf8("rl_check"))
        self.rl_rr_horiz_layout.addWidget(self.rl_check)
        self.rl_n_label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.rl_n_label.setObjectName(_fromUtf8("rl_n_label"))
        self.rl_rr_horiz_layout.addWidget(self.rl_n_label)
        self.rl_n = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.rl_n.setMaxLength(7)
        self.rl_n.setObjectName(_fromUtf8("rl_n"))
        self.rl_rr_horiz_layout.addWidget(self.rl_n)
        self.rr_label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.rr_label.setMinimumSize(QtCore.QSize(111, 0))
        self.rr_label.setObjectName(_fromUtf8("rr_label"))
        self.rl_rr_horiz_layout.addWidget(self.rr_label)
        self.rr_check = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.rr_check.setText(_fromUtf8(""))
        self.rr_check.setObjectName(_fromUtf8("rr_check"))
        self.rl_rr_horiz_layout.addWidget(self.rr_check)
        self.rr_n_label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.rr_n_label.setObjectName(_fromUtf8("rr_n_label"))
        self.rl_rr_horiz_layout.addWidget(self.rr_n_label)
        self.rr_n = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.rr_n.setMaxLength(7)
        self.rr_n.setObjectName(_fromUtf8("rr_n"))
        self.rl_rr_horiz_layout.addWidget(self.rr_n)
        self.method_comparison_layout.addLayout(self.rl_rr_horiz_layout)
        self.rm_trap_horiz_layout = QtGui.QHBoxLayout()
        self.rm_trap_horiz_layout.setObjectName(_fromUtf8("rm_trap_horiz_layout"))
        self.rm_label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.rm_label.setMinimumSize(QtCore.QSize(111, 0))
        self.rm_label.setObjectName(_fromUtf8("rm_label"))
        self.rm_trap_horiz_layout.addWidget(self.rm_label)
        self.rm_check = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.rm_check.setText(_fromUtf8(""))
        self.rm_check.setObjectName(_fromUtf8("rm_check"))
        self.rm_trap_horiz_layout.addWidget(self.rm_check)
        self.rm_n_label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.rm_n_label.setObjectName(_fromUtf8("rm_n_label"))
        self.rm_trap_horiz_layout.addWidget(self.rm_n_label)
        self.rm_n = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.rm_n.setMaxLength(7)
        self.rm_n.setObjectName(_fromUtf8("rm_n"))
        self.rm_trap_horiz_layout.addWidget(self.rm_n)
        self.trap_label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.trap_label.setMinimumSize(QtCore.QSize(111, 0))
        self.trap_label.setObjectName(_fromUtf8("trap_label"))
        self.rm_trap_horiz_layout.addWidget(self.trap_label)
        self.trap_check = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.trap_check.setText(_fromUtf8(""))
        self.trap_check.setObjectName(_fromUtf8("trap_check"))
        self.rm_trap_horiz_layout.addWidget(self.trap_check)
        self.trap_n_label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.trap_n_label.setObjectName(_fromUtf8("trap_n_label"))
        self.rm_trap_horiz_layout.addWidget(self.trap_n_label)
        self.trap_n = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.trap_n.setMaxLength(7)
        self.trap_n.setObjectName(_fromUtf8("trap_n"))
        self.rm_trap_horiz_layout.addWidget(self.trap_n)
        self.method_comparison_layout.addLayout(self.rm_trap_horiz_layout)
        self.simp_gauss_horiz_layout = QtGui.QHBoxLayout()
        self.simp_gauss_horiz_layout.setObjectName(_fromUtf8("simp_gauss_horiz_layout"))
        self.simp_label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.simp_label.setMinimumSize(QtCore.QSize(111, 0))
        self.simp_label.setObjectName(_fromUtf8("simp_label"))
        self.simp_gauss_horiz_layout.addWidget(self.simp_label)
        self.simp_check = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.simp_check.setText(_fromUtf8(""))
        self.simp_check.setObjectName(_fromUtf8("simp_check"))
        self.simp_gauss_horiz_layout.addWidget(self.simp_check)
        self.simp_n_label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.simp_n_label.setObjectName(_fromUtf8("simp_n_label"))
        self.simp_gauss_horiz_layout.addWidget(self.simp_n_label)
        self.simp_n = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.simp_n.setMaxLength(7)
        self.simp_n.setObjectName(_fromUtf8("simp_n"))
        self.simp_gauss_horiz_layout.addWidget(self.simp_n)
        self.gauss_label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.gauss_label.setMinimumSize(QtCore.QSize(111, 0))
        self.gauss_label.setObjectName(_fromUtf8("gauss_label"))
        self.simp_gauss_horiz_layout.addWidget(self.gauss_label)
        self.gauss_check = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.gauss_check.setText(_fromUtf8(""))
        self.gauss_check.setObjectName(_fromUtf8("gauss_check"))
        self.simp_gauss_horiz_layout.addWidget(self.gauss_check)
        self.gauss_n_label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.gauss_n_label.setObjectName(_fromUtf8("gauss_n_label"))
        self.simp_gauss_horiz_layout.addWidget(self.gauss_n_label)
        self.gauss_n = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.gauss_n.setMaxLength(7)
        self.gauss_n.setObjectName(_fromUtf8("gauss_n"))
        self.simp_gauss_horiz_layout.addWidget(self.gauss_n)
        self.method_comparison_layout.addLayout(self.simp_gauss_horiz_layout)
        self.monte_horiz_layout = QtGui.QHBoxLayout()
        self.monte_horiz_layout.setObjectName(_fromUtf8("monte_horiz_layout"))
        self.monte_label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.monte_label.setMinimumSize(QtCore.QSize(111, 0))
        self.monte_label.setObjectName(_fromUtf8("monte_label"))
        self.monte_horiz_layout.addWidget(self.monte_label)
        self.monte_check = QtGui.QCheckBox(self.verticalLayoutWidget_5)
        self.monte_check.setText(_fromUtf8(""))
        self.monte_check.setObjectName(_fromUtf8("monte_check"))
        self.monte_horiz_layout.addWidget(self.monte_check)
        self.mont_n_label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.mont_n_label.setObjectName(_fromUtf8("mont_n_label"))
        self.monte_horiz_layout.addWidget(self.mont_n_label)
        self.monte_n = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.monte_n.setMaxLength(7)
        self.monte_n.setObjectName(_fromUtf8("monte_n"))
        self.monte_horiz_layout.addWidget(self.monte_n)
        spacerItem = QtGui.QSpacerItem(250, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.monte_horiz_layout.addItem(spacerItem)
        self.method_comparison_layout.addLayout(self.monte_horiz_layout)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        main_window.setWindowTitle(QtGui.QApplication.translate("main_window", "Numerical Integration Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.rb1.setText(QtGui.QApplication.translate("main_window", "Riemman (Left)", None, QtGui.QApplication.UnicodeUTF8))
        self.rb2.setText(QtGui.QApplication.translate("main_window", "Riemman (Right)", None, QtGui.QApplication.UnicodeUTF8))
        self.rb3.setText(QtGui.QApplication.translate("main_window", "Riemman (Mid)", None, QtGui.QApplication.UnicodeUTF8))
        self.rb4.setText(QtGui.QApplication.translate("main_window", "Trapezoidal", None, QtGui.QApplication.UnicodeUTF8))
        self.rb5.setText(QtGui.QApplication.translate("main_window", "Simpson\'s", None, QtGui.QApplication.UnicodeUTF8))
        self.rb6.setText(QtGui.QApplication.translate("main_window", "Gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.rb7.setText(QtGui.QApplication.translate("main_window", "Monte Carlo", None, QtGui.QApplication.UnicodeUTF8))
        self.x_Left_Label.setText(QtGui.QApplication.translate("main_window", "X-Left", None, QtGui.QApplication.UnicodeUTF8))
        self.x_Left_Line_Edit.setText(QtGui.QApplication.translate("main_window", "-7.0", None, QtGui.QApplication.UnicodeUTF8))
        self.x_Right_Label.setText(QtGui.QApplication.translate("main_window", "X-Right", None, QtGui.QApplication.UnicodeUTF8))
        self.x_Right_Line_Edit.setText(QtGui.QApplication.translate("main_window", "7.0", None, QtGui.QApplication.UnicodeUTF8))
        self.update_button.setText(QtGui.QApplication.translate("main_window", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.func_label.setText(QtGui.QApplication.translate("main_window", "f(x):", None, QtGui.QApplication.UnicodeUTF8))
        self.f_input.setText(QtGui.QApplication.translate("main_window", "x^2", None, QtGui.QApplication.UnicodeUTF8))
        self.adiv_label.setText(QtGui.QApplication.translate("main_window", "F(x):", None, QtGui.QApplication.UnicodeUTF8))
        self.F_input.setText(QtGui.QApplication.translate("main_window", "x^3/3", None, QtGui.QApplication.UnicodeUTF8))
        self.calculated_label.setText(QtGui.QApplication.translate("main_window", "Result:", None, QtGui.QApplication.UnicodeUTF8))
        self.calculated_result.setText(QtGui.QApplication.translate("main_window", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.error_label.setText(QtGui.QApplication.translate("main_window", "Error:", None, QtGui.QApplication.UnicodeUTF8))
        self.error_calculated.setText(QtGui.QApplication.translate("main_window", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.quad_method_table.setSortingEnabled(False)
        item = self.quad_method_table.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("main_window", "RL", None, QtGui.QApplication.UnicodeUTF8))
        item = self.quad_method_table.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("main_window", "RR", None, QtGui.QApplication.UnicodeUTF8))
        item = self.quad_method_table.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("main_window", "RM", None, QtGui.QApplication.UnicodeUTF8))
        item = self.quad_method_table.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("main_window", "Trap", None, QtGui.QApplication.UnicodeUTF8))
        item = self.quad_method_table.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("main_window", "Simp", None, QtGui.QApplication.UnicodeUTF8))
        item = self.quad_method_table.verticalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("main_window", "Gauss", None, QtGui.QApplication.UnicodeUTF8))
        item = self.quad_method_table.verticalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("main_window", "Monte", None, QtGui.QApplication.UnicodeUTF8))
        item = self.quad_method_table.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("main_window", "Approx.", None, QtGui.QApplication.UnicodeUTF8))
        item = self.quad_method_table.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("main_window", "Error", None, QtGui.QApplication.UnicodeUTF8))
        item = self.quad_method_table.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("main_window", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.rl_label.setText(QtGui.QApplication.translate("main_window", "Riemman (Left)", None, QtGui.QApplication.UnicodeUTF8))
        self.rl_n_label.setText(QtGui.QApplication.translate("main_window", "n=", None, QtGui.QApplication.UnicodeUTF8))
        self.rl_n.setText(QtGui.QApplication.translate("main_window", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.rr_label.setText(QtGui.QApplication.translate("main_window", "Riemman (Right)", None, QtGui.QApplication.UnicodeUTF8))
        self.rr_n_label.setText(QtGui.QApplication.translate("main_window", "n=", None, QtGui.QApplication.UnicodeUTF8))
        self.rr_n.setText(QtGui.QApplication.translate("main_window", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.rm_label.setText(QtGui.QApplication.translate("main_window", "Riemman (Mid)", None, QtGui.QApplication.UnicodeUTF8))
        self.rm_n_label.setText(QtGui.QApplication.translate("main_window", "n=", None, QtGui.QApplication.UnicodeUTF8))
        self.rm_n.setText(QtGui.QApplication.translate("main_window", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.trap_label.setText(QtGui.QApplication.translate("main_window", "Trapezoidal", None, QtGui.QApplication.UnicodeUTF8))
        self.trap_n_label.setText(QtGui.QApplication.translate("main_window", "n=", None, QtGui.QApplication.UnicodeUTF8))
        self.trap_n.setText(QtGui.QApplication.translate("main_window", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.simp_label.setText(QtGui.QApplication.translate("main_window", "Simpson\'s", None, QtGui.QApplication.UnicodeUTF8))
        self.simp_n_label.setText(QtGui.QApplication.translate("main_window", "n=", None, QtGui.QApplication.UnicodeUTF8))
        self.simp_n.setText(QtGui.QApplication.translate("main_window", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.gauss_label.setText(QtGui.QApplication.translate("main_window", "Gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.gauss_n_label.setText(QtGui.QApplication.translate("main_window", "n=", None, QtGui.QApplication.UnicodeUTF8))
        self.gauss_n.setText(QtGui.QApplication.translate("main_window", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.monte_label.setText(QtGui.QApplication.translate("main_window", "Monte Carlo", None, QtGui.QApplication.UnicodeUTF8))
        self.mont_n_label.setText(QtGui.QApplication.translate("main_window", "n=", None, QtGui.QApplication.UnicodeUTF8))
        self.monte_n.setText(QtGui.QApplication.translate("main_window", "1000", None, QtGui.QApplication.UnicodeUTF8))
